### ISSUE TITLE
Same items with different NBT tags are not stacking up together

### ISSUE THREAD

**Issue by bricebasty** [haveric/StackableItems#142]
Here is my items.yml

```
allWorlds:
  player: {}
  group:
    testGroup:
      MIN: -1
      MAX: -1
  inventory:
    chest:
      MIN: -1
      MAX: -1
  default:
    MIN: 64
    MAX: -1
```

Items (like potatoes or end rods, or literally anything) are making 2 different stacks because one of them has 1 NBT tag and the other one hasn't. Will try to provide a screenshot.

I'm trying to find a workaround by triggering the activation of the plugin only on the items which need it (like armors, swords, buckets, enderpearls, potions).
