### ISSUE TITLE
Custom NBT support

### ISSUE THREAD

**Issue by Patbox** [haveric/StackableItems#147]
Maybe add support for enabling custom stacking to items with additional nbt.

Config exaple:
```
allWorlds:
  default:
    snowball: 32
    snowball{CustomModelData:1}: 64
```
