### ISSUE TITLE
Shift-double-clicking on items in your own inventory causes them to drop

### ISSUE THREAD

**Issue by Pugabyte** [haveric/StackableItems#161]
https://i.imgur.com/PRGvcPF.gifv

ProjectEden/Issues#679

**Comment by haveric** [comment]
Can you provide your items.yml file?

**Comment by Pugabyte** [comment]
```
allWorlds:
  default:
    mushroom_stew: 16
    rabbit_stew: 16
    beetroot_soup: 16
    suspicious_stew: 4
```
